image: maven:3.6.3-jdk-11

stages:
- build
- test

cache:
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - mvn clean package -DskipTests=true

test:
  stage: test
  script:
  - mvn test -Pweb-execution -Dsuite=local -Dtarget=local -Dtestng.dtd.http=true